name: build

on: [push]

defaults:
  run:
    shell: csh -e {0}

jobs:
  print-jg-version:
    runs-on: [self-hosted, Linux, X64]
    
    steps:
      - uses: actions/checkout@v5
      
      - name: Run Jasper 
        run: |
          source /apps/cc/user_env/tools_cshrc
          echo "Current user: $USER"
          echo "Current dir: $PWD"
          echo "PATH: $PATH"
          echo "Modules command test:"
          which module
          module list  
          
      # Upload artifact
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: jg-logs        # Artifact name
          path: jg_version.log # File or folder to upload
