name: build

on: [push]

defaults:
  run:
    shell: csh -e {0}

jobs:
  print-jg-version:
    runs-on: [self-hosted, Linux, X64]
    
    steps:
      - uses: actions/checkout@v5
      - name: Debug + Run Jasper
        run: |
          set verbose
          set echo
          source /apps/cc/user_env/tools_cshrc
          echo "Current user: $USER"
          echo "Current dir: $PWD"
          echo "PATH: $PATH"
          echo "Modules command test:"
          which module
          module list
          echo 'Loading jasper'
          module load jasper/2406/24.06.001
          echo 'Printing version'
          jg -version |& tee jg_version.log

     
