
name: simple-test

on: [push]

jobs:
  run-command:
    runs-on: [self-hosted, Linux, X64]

    steps:
      # Checkout code
      - uses: actions/checkout@v5

      # Run a simple command and log
      - name: Run command and capture output
        shell: csh {0}   # using your csh shell
        run: |
          echo "Hello from self-hosted runner"
          date |& tee run.log
          echo "Listing current dir"
          ls -al |& tee -a run.log

      # Upload the log as artifact
      - name: Upload log artifact
        uses: actions/upload-artifact@v4
        with:
          name: run-log
          path: run.log
